// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type AlertHistory struct {
	ID             int64
	ProjectID      string
	ProjectName    string
	AlertType      string
	Status         sql.NullString
	Message        sql.NullString
	BalanceValue   sql.NullFloat64
	ThresholdValue sql.NullFloat64
	Timestamp      sql.NullTime
}

type AppSetting struct {
	SettingKey   string
	SettingValue string
}

type BalanceHistory struct {
	ID          int64
	ProjectID   string
	ProjectName string
	Provider    string
	Balance     float64
	Threshold   sql.NullFloat64
	BalanceType sql.NullString
	NeedAlarm   sql.NullBool
	Timestamp   sql.NullTime
}

type EmailAlertHistory struct {
	ID              int64
	Mailbox         string
	Sender          string
	Subject         string
	Date            string
	ServiceName     sql.NullString
	Amount          sql.NullFloat64
	MatchedKeywords sql.NullString
	AlertSent       sql.NullBool
	Timestamp       sql.NullTime
}

type EmailConfig struct {
	ID        int64
	Name      string
	Host      string
	Port      sql.NullInt64
	Username  string
	Password  string
	UseSsl    sql.NullBool
	Enabled   sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type EmailSuppression struct {
	ID        int64
	Mailbox   string
	Sender    string
	CreatedAt sql.NullTime
}

type ProjectConfig struct {
	ID           int64
	Name         string
	OwnerProject sql.NullString
	Provider     string
	ApiKey       string
	Threshold    sql.NullFloat64
	Type         sql.NullString
	Enabled      sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type PushSubscription struct {
	ID        int64
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt sql.NullTime
}

type SubscriptionConfig struct {
	ID              int64
	Name            string
	OwnerProject    sql.NullString
	CycleType       sql.NullString
	RenewalDay      sql.NullInt64
	AlertDaysBefore sql.NullInt64
	Amount          sql.NullFloat64
	Enabled         sql.NullBool
	LastRenewedDate sql.NullString
	SnoozedUntil    sql.NullString
	Timezone        sql.NullString
	WebhookUrl      sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}
