// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postgres.sql

package postgres

import (
	"context"
	"database/sql"
)

const addEmailSuppression = `-- name: AddEmailSuppression :exec
INSERT INTO email_suppressions (mailbox, sender, created_at) VALUES ($1, $2, $3)
ON CONFLICT (mailbox, sender) DO NOTHING
`

type AddEmailSuppressionParams struct {
	Mailbox   string
	Sender    string
	CreatedAt sql.NullTime
}

func (q *Queries) AddEmailSuppression(ctx context.Context, arg AddEmailSuppressionParams) error {
	_, err := q.db.ExecContext(ctx, addEmailSuppression, arg.Mailbox, arg.Sender, arg.CreatedAt)
	return err
}

const countAlerts = `-- name: CountAlerts :one
SELECT COUNT(*) FROM alert_history WHERE "timestamp" >= $1
`

func (q *Queries) CountAlerts(ctx context.Context, since sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlerts, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlertsByProject = `-- name: CountAlertsByProject :many
SELECT project_name, COUNT(*) AS count FROM alert_history
WHERE "timestamp" >= $1
GROUP BY project_name
ORDER BY count DESC
LIMIT 10
`

type CountAlertsByProjectRow struct {
	ProjectName string
	Count       int64
}

func (q *Queries) CountAlertsByProject(ctx context.Context, since sql.NullTime) ([]CountAlertsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, countAlertsByProject, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAlertsByProjectRow{}
	for rows.Next() {
		var i CountAlertsByProjectRow
		if err := rows.Scan(&i.ProjectName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAlertsByType = `-- name: CountAlertsByType :many
SELECT alert_type, COUNT(*) AS count FROM alert_history
WHERE "timestamp" >= $1
GROUP BY alert_type
`

type CountAlertsByTypeRow struct {
	AlertType string
	Count     int64
}

func (q *Queries) CountAlertsByType(ctx context.Context, since sql.NullTime) ([]CountAlertsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countAlertsByType, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAlertsByTypeRow{}
	for rows.Next() {
		var i CountAlertsByTypeRow
		if err := rows.Scan(&i.AlertType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRecentAlerts = `-- name: CountRecentAlerts :one
SELECT COUNT(*) FROM alert_history
WHERE project_id = $1
  AND alert_type = $2
  AND status = $3
  AND "timestamp" >= $4
`

type CountRecentAlertsParams struct {
	ProjectID string
	AlertType string
	Status    sql.NullString
	Since     sql.NullTime
}

func (q *Queries) CountRecentAlerts(ctx context.Context, arg CountRecentAlertsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentAlerts,
		arg.ProjectID,
		arg.AlertType,
		arg.Status,
		arg.Since,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentEmailAlerts = `-- name: CountRecentEmailAlerts :one
SELECT COUNT(*) FROM email_alert_history
WHERE mailbox = $1
  AND sender = $2
  AND subject = $3
  AND date = $4
  AND alert_sent = TRUE
  AND "timestamp" >= $5
`

type CountRecentEmailAlertsParams struct {
	Mailbox string
	Sender  string
	Subject string
	Date    string
	Since   sql.NullTime
}

func (q *Queries) CountRecentEmailAlerts(ctx context.Context, arg CountRecentEmailAlertsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentEmailAlerts,
		arg.Mailbox,
		arg.Sender,
		arg.Subject,
		arg.Date,
		arg.Since,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmailConfig = `-- name: DeleteEmailConfig :exec
DELETE FROM email_config WHERE name = $1
`

func (q *Queries) DeleteEmailConfig(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailConfig, name)
	return err
}

const deleteEmailSuppression = `-- name: DeleteEmailSuppression :exec
DELETE FROM email_suppressions WHERE mailbox = $1 AND sender = $2
`

type DeleteEmailSuppressionParams struct {
	Mailbox string
	Sender  string
}

func (q *Queries) DeleteEmailSuppression(ctx context.Context, arg DeleteEmailSuppressionParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailSuppression, arg.Mailbox, arg.Sender)
	return err
}

const deleteProjectConfig = `-- name: DeleteProjectConfig :exec
DELETE FROM project_config WHERE name = $1
`

func (q *Queries) DeleteProjectConfig(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectConfig, name)
	return err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscription(ctx context.Context, endpoint string) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscription, endpoint)
	return err
}

const deleteSubscriptionConfig = `-- name: DeleteSubscriptionConfig :exec
DELETE FROM subscription_config WHERE name = $1
`

func (q *Queries) DeleteSubscriptionConfig(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriptionConfig, name)
	return err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT setting_value FROM app_settings WHERE setting_key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, settingKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, settingKey)
	var setting_value string
	err := row.Scan(&setting_value)
	return setting_value, err
}

const insertAlertHistory = `-- name: InsertAlertHistory :exec
INSERT INTO alert_history (
    project_id, project_name, alert_type, status, message, balance_value, threshold_value, "timestamp"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAlertHistoryParams struct {
	ProjectID      string
	ProjectName    string
	AlertType      string
	Status         sql.NullString
	Message        sql.NullString
	BalanceValue   sql.NullFloat64
	ThresholdValue sql.NullFloat64
	Timestamp      sql.NullTime
}

func (q *Queries) InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertAlertHistory,
		arg.ProjectID,
		arg.ProjectName,
		arg.AlertType,
		arg.Status,
		arg.Message,
		arg.BalanceValue,
		arg.ThresholdValue,
		arg.Timestamp,
	)
	return err
}

const insertBalanceHistory = `-- name: InsertBalanceHistory :exec
INSERT INTO balance_history (
    project_id, project_name, provider, balance, threshold, balance_type, need_alarm, "timestamp"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertBalanceHistoryParams struct {
	ProjectID   string
	ProjectName string
	Provider    string
	Balance     float64
	Threshold   sql.NullFloat64
	BalanceType sql.NullString
	NeedAlarm   sql.NullBool
	Timestamp   sql.NullTime
}

func (q *Queries) InsertBalanceHistory(ctx context.Context, arg InsertBalanceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertBalanceHistory,
		arg.ProjectID,
		arg.ProjectName,
		arg.Provider,
		arg.Balance,
		arg.Threshold,
		arg.BalanceType,
		arg.NeedAlarm,
		arg.Timestamp,
	)
	return err
}

const insertEmailAlertHistory = `-- name: InsertEmailAlertHistory :exec
INSERT INTO email_alert_history (
    mailbox, sender, subject, date, service_name, amount, matched_keywords, alert_sent, "timestamp"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertEmailAlertHistoryParams struct {
	Mailbox         string
	Sender          string
	Subject         string
	Date            string
	ServiceName     sql.NullString
	Amount          sql.NullFloat64
	MatchedKeywords sql.NullString
	AlertSent       sql.NullBool
	Timestamp       sql.NullTime
}

func (q *Queries) InsertEmailAlertHistory(ctx context.Context, arg InsertEmailAlertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertEmailAlertHistory,
		arg.Mailbox,
		arg.Sender,
		arg.Subject,
		arg.Date,
		arg.ServiceName,
		arg.Amount,
		arg.MatchedKeywords,
		arg.AlertSent,
		arg.Timestamp,
	)
	return err
}

const listAlertHistory = `-- name: ListAlertHistory :many
SELECT id, project_id, project_name, alert_type, status, message, balance_value, threshold_value, timestamp FROM alert_history
WHERE "timestamp" >= $1
  AND ($2::text = '' OR project_id = $2::text)
  AND ($3::text = '' OR alert_type = $3::text)
ORDER BY "timestamp" DESC
LIMIT $4
`

type ListAlertHistoryParams struct {
	Since     sql.NullTime
	ProjectID string
	AlertType string
	RowLimit  int32
}

func (q *Queries) ListAlertHistory(ctx context.Context, arg ListAlertHistoryParams) ([]AlertHistory, error) {
	rows, err := q.db.QueryContext(ctx, listAlertHistory,
		arg.Since,
		arg.ProjectID,
		arg.AlertType,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertHistory{}
	for rows.Next() {
		var i AlertHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.AlertType,
			&i.Status,
			&i.Message,
			&i.BalanceValue,
			&i.ThresholdValue,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceHistory = `-- name: ListBalanceHistory :many
SELECT id, project_id, project_name, provider, balance, threshold, balance_type, need_alarm, timestamp FROM balance_history
WHERE "timestamp" >= $1
  AND ($2::text = '' OR project_id = $2::text)
  AND ($3::text = '' OR provider = $3::text)
ORDER BY "timestamp" DESC
LIMIT $4
`

type ListBalanceHistoryParams struct {
	Since     sql.NullTime
	ProjectID string
	Provider  string
	RowLimit  int32
}

func (q *Queries) ListBalanceHistory(ctx context.Context, arg ListBalanceHistoryParams) ([]BalanceHistory, error) {
	rows, err := q.db.QueryContext(ctx, listBalanceHistory,
		arg.Since,
		arg.ProjectID,
		arg.Provider,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceHistory{}
	for rows.Next() {
		var i BalanceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Provider,
			&i.Balance,
			&i.Threshold,
			&i.BalanceType,
			&i.NeedAlarm,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceSeries = `-- name: ListBalanceSeries :many
SELECT id, project_id, project_name, provider, balance, threshold, balance_type, need_alarm, timestamp FROM balance_history
WHERE "timestamp" >= $1
ORDER BY "timestamp"
`

func (q *Queries) ListBalanceSeries(ctx context.Context, since sql.NullTime) ([]BalanceHistory, error) {
	rows, err := q.db.QueryContext(ctx, listBalanceSeries, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceHistory{}
	for rows.Next() {
		var i BalanceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Provider,
			&i.Balance,
			&i.Threshold,
			&i.BalanceType,
			&i.NeedAlarm,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceTrend = `-- name: ListBalanceTrend :many
SELECT id, project_id, project_name, provider, balance, threshold, balance_type, need_alarm, timestamp FROM balance_history
WHERE project_id = $1 AND "timestamp" >= $2
ORDER BY "timestamp"
`

type ListBalanceTrendParams struct {
	ProjectID string
	Since     sql.NullTime
}

func (q *Queries) ListBalanceTrend(ctx context.Context, arg ListBalanceTrendParams) ([]BalanceHistory, error) {
	rows, err := q.db.QueryContext(ctx, listBalanceTrend, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceHistory{}
	for rows.Next() {
		var i BalanceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Provider,
			&i.Balance,
			&i.Threshold,
			&i.BalanceType,
			&i.NeedAlarm,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailAlertHistory = `-- name: ListEmailAlertHistory :many
SELECT id, mailbox, sender, subject, date, service_name, amount, matched_keywords, alert_sent, timestamp FROM email_alert_history
WHERE "timestamp" >= $1
  AND ($2::text = '' OR mailbox = $2::text)
ORDER BY "timestamp" DESC
LIMIT $3
`

type ListEmailAlertHistoryParams struct {
	Since    sql.NullTime
	Mailbox  string
	RowLimit int32
}

func (q *Queries) ListEmailAlertHistory(ctx context.Context, arg ListEmailAlertHistoryParams) ([]EmailAlertHistory, error) {
	rows, err := q.db.QueryContext(ctx, listEmailAlertHistory, arg.Since, arg.Mailbox, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailAlertHistory{}
	for rows.Next() {
		var i EmailAlertHistory
		if err := rows.Scan(
			&i.ID,
			&i.Mailbox,
			&i.Sender,
			&i.Subject,
			&i.Date,
			&i.ServiceName,
			&i.Amount,
			&i.MatchedKeywords,
			&i.AlertSent,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailConfigs = `-- name: ListEmailConfigs :many
SELECT id, name, host, port, username, password, use_ssl, enabled, created_at, updated_at FROM email_config ORDER BY id
`

func (q *Queries) ListEmailConfigs(ctx context.Context) ([]EmailConfig, error) {
	rows, err := q.db.QueryContext(ctx, listEmailConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailConfig{}
	for rows.Next() {
		var i EmailConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.UseSsl,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailSuppressions = `-- name: ListEmailSuppressions :many
SELECT mailbox, sender FROM email_suppressions ORDER BY id
`

type ListEmailSuppressionsRow struct {
	Mailbox string
	Sender  string
}

func (q *Queries) ListEmailSuppressions(ctx context.Context) ([]ListEmailSuppressionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailSuppressions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailSuppressionsRow{}
	for rows.Next() {
		var i ListEmailSuppressionsRow
		if err := rows.Scan(&i.Mailbox, &i.Sender); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectConfigs = `-- name: ListProjectConfigs :many

SELECT id, name, owner_project, provider, api_key, threshold, type, enabled, created_at, updated_at FROM project_config ORDER BY id
`

// NOTE: keep this file ASCII-only. sqlc computes byte offsets from rune positions
// when slicing query text, so non-ASCII comments corrupt the parse. Design notes in Chinese
// live in internal/store/schema/*.sql and in the Go adapters.
func (q *Queries) ListProjectConfigs(ctx context.Context) ([]ProjectConfig, error) {
	rows, err := q.db.QueryContext(ctx, listProjectConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectConfig{}
	for rows.Next() {
		var i ProjectConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerProject,
			&i.Provider,
			&i.ApiKey,
			&i.Threshold,
			&i.Type,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT endpoint, p256dh, auth FROM push_subscriptions ORDER BY id
`

type ListPushSubscriptionsRow struct {
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) ListPushSubscriptions(ctx context.Context) ([]ListPushSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushSubscriptionsRow{}
	for rows.Next() {
		var i ListPushSubscriptionsRow
		if err := rows.Scan(&i.Endpoint, &i.P256dh, &i.Auth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionConfigs = `-- name: ListSubscriptionConfigs :many
SELECT id, name, owner_project, cycle_type, renewal_day, alert_days_before, amount, enabled, last_renewed_date, snoozed_until, timezone, webhook_url, created_at, updated_at FROM subscription_config ORDER BY id
`

func (q *Queries) ListSubscriptionConfigs(ctx context.Context) ([]SubscriptionConfig, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionConfig{}
	for rows.Next() {
		var i SubscriptionConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerProject,
			&i.CycleType,
			&i.RenewalDay,
			&i.AlertDaysBefore,
			&i.Amount,
			&i.Enabled,
			&i.LastRenewedDate,
			&i.SnoozedUntil,
			&i.Timezone,
			&i.WebhookUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppSetting = `-- name: SetAppSetting :exec
INSERT INTO app_settings (setting_key, setting_value) VALUES ($1, $2)
ON CONFLICT (setting_key) DO UPDATE SET setting_value = excluded.setting_value
`

type SetAppSettingParams struct {
	SettingKey   string
	SettingValue string
}

func (q *Queries) SetAppSetting(ctx context.Context, arg SetAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, setAppSetting, arg.SettingKey, arg.SettingValue)
	return err
}

const setSubscriptionSnooze = `-- name: SetSubscriptionSnooze :exec
UPDATE subscription_config SET snoozed_until = $1 WHERE name = $2
`

type SetSubscriptionSnoozeParams struct {
	SnoozedUntil sql.NullString
	Name         string
}

func (q *Queries) SetSubscriptionSnooze(ctx context.Context, arg SetSubscriptionSnoozeParams) error {
	_, err := q.db.ExecContext(ctx, setSubscriptionSnooze, arg.SnoozedUntil, arg.Name)
	return err
}

const updateEmailPassword = `-- name: UpdateEmailPassword :exec
UPDATE email_config SET password = $1 WHERE name = $2
`

type UpdateEmailPasswordParams struct {
	Password string
	Name     string
}

func (q *Queries) UpdateEmailPassword(ctx context.Context, arg UpdateEmailPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailPassword, arg.Password, arg.Name)
	return err
}

const updateProjectAPIKey = `-- name: UpdateProjectAPIKey :exec
UPDATE project_config SET api_key = $1 WHERE name = $2
`

type UpdateProjectAPIKeyParams struct {
	ApiKey string
	Name   string
}

func (q *Queries) UpdateProjectAPIKey(ctx context.Context, arg UpdateProjectAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectAPIKey, arg.ApiKey, arg.Name)
	return err
}

const updateSubscriptionTimezone = `-- name: UpdateSubscriptionTimezone :exec
UPDATE subscription_config SET timezone = $1 WHERE name = $2
`

type UpdateSubscriptionTimezoneParams struct {
	Timezone sql.NullString
	Name     string
}

func (q *Queries) UpdateSubscriptionTimezone(ctx context.Context, arg UpdateSubscriptionTimezoneParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionTimezone, arg.Timezone, arg.Name)
	return err
}

const updateSubscriptionWebhook = `-- name: UpdateSubscriptionWebhook :exec
UPDATE subscription_config SET webhook_url = $1 WHERE name = $2
`

type UpdateSubscriptionWebhookParams struct {
	WebhookUrl sql.NullString
	Name       string
}

func (q *Queries) UpdateSubscriptionWebhook(ctx context.Context, arg UpdateSubscriptionWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionWebhook, arg.WebhookUrl, arg.Name)
	return err
}

const upsertEmailConfig = `-- name: UpsertEmailConfig :exec
INSERT INTO email_config (
    name, host, port, username, password, use_ssl, enabled, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (name) DO UPDATE SET
    host = excluded.host,
    port = excluded.port,
    username = excluded.username,
    password = excluded.password,
    use_ssl = excluded.use_ssl,
    enabled = excluded.enabled,
    updated_at = excluded.updated_at
`

type UpsertEmailConfigParams struct {
	Name      string
	Host      string
	Port      sql.NullInt64
	Username  string
	Password  string
	UseSsl    sql.NullBool
	Enabled   sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) UpsertEmailConfig(ctx context.Context, arg UpsertEmailConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmailConfig,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.UseSsl,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectConfig = `-- name: UpsertProjectConfig :exec
INSERT INTO project_config (
    name, owner_project, provider, api_key, threshold, type, enabled, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (name) DO UPDATE SET
    owner_project = excluded.owner_project,
    provider = excluded.provider,
    api_key = excluded.api_key,
    threshold = excluded.threshold,
    type = excluded.type,
    enabled = excluded.enabled,
    updated_at = excluded.updated_at
`

type UpsertProjectConfigParams struct {
	Name         string
	OwnerProject sql.NullString
	Provider     string
	ApiKey       string
	Threshold    sql.NullFloat64
	Type         sql.NullString
	Enabled      sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) UpsertProjectConfig(ctx context.Context, arg UpsertProjectConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectConfig,
		arg.Name,
		arg.OwnerProject,
		arg.Provider,
		arg.ApiKey,
		arg.Threshold,
		arg.Type,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (endpoint, p256dh, auth, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint) DO UPDATE SET
    p256dh = excluded.p256dh,
    auth = excluded.auth,
    created_at = excluded.created_at
`

type UpsertPushSubscriptionParams struct {
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt sql.NullTime
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushSubscription,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.CreatedAt,
	)
	return err
}

const upsertSubscriptionConfig = `-- name: UpsertSubscriptionConfig :exec
INSERT INTO subscription_config (
    name, owner_project, cycle_type, renewal_day, alert_days_before, amount, enabled,
    last_renewed_date, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (name) DO UPDATE SET
    owner_project = excluded.owner_project,
    cycle_type = excluded.cycle_type,
    renewal_day = excluded.renewal_day,
    alert_days_before = excluded.alert_days_before,
    amount = excluded.amount,
    enabled = excluded.enabled,
    last_renewed_date = excluded.last_renewed_date,
    updated_at = excluded.updated_at
`

type UpsertSubscriptionConfigParams struct {
	Name            string
	OwnerProject    sql.NullString
	CycleType       sql.NullString
	RenewalDay      sql.NullInt64
	AlertDaysBefore sql.NullInt64
	Amount          sql.NullFloat64
	Enabled         sql.NullBool
	LastRenewedDate sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

func (q *Queries) UpsertSubscriptionConfig(ctx context.Context, arg UpsertSubscriptionConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscriptionConfig,
		arg.Name,
		arg.OwnerProject,
		arg.CycleType,
		arg.RenewalDay,
		arg.AlertDaysBefore,
		arg.Amount,
		arg.Enabled,
		arg.LastRenewedDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
